service: perfect-projects-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: perfect-project-backend-role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'iam:DeleteBucket'
  deploymentBucket:
    name: perfect-project-backend

custom:
  wsgi:
    app: backend.app
    packRequirements: false

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
          authorizer:
            type: TOKEN
            name: authorizerFun
            identitySource: method.request.header.Authorization

plugins:
  - serverless-deployment-bucket
  - serverless-wsgi
  - serverless-python-requirements
