service: perfect-projects-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: perfect-project-backend-role
      statements:
        - Effect: 'Allow'
          Action: '*'
          Resource: '*'
  deploymentBucket:
    name: perfect-project-backend

custom:
  wsgi:
    app: backend.app

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-deployment-bucket
  - serverless-wsgi
  - serverless-python-requirements
